# Generated by Django 4.1.7 on 2023-05-28 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="名無しのハンター", max_length=30)),
                ("content", models.TextField(max_length=1000, verbose_name="本文")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, upload_to="images", verbose_name="画像"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="名無しのハンター", max_length=30)),
                ("content", models.TextField(max_length=1000, verbose_name="本文")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, upload_to="images", verbose_name="画像"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="名無しのハンター", max_length=30)),
                ("content", models.TextField(max_length=1000, verbose_name="本文")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, upload_to="images", verbose_name="画像"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post_4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="名無しのハンター", max_length=30)),
                ("content", models.TextField(max_length=1000, verbose_name="本文")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, upload_to="images", verbose_name="画像"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment_4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        default="名無しのハンター", max_length=30, verbose_name="名前"
                    ),
                ),
                ("message", models.TextField(max_length=1000, verbose_name="本文")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mhsb.post_4",
                        verbose_name="対象記事",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",),},
        ),
        migrations.CreateModel(
            name="Comment_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        default="名無しのハンター", max_length=30, verbose_name="名前"
                    ),
                ),
                ("message", models.TextField(max_length=1000, verbose_name="本文")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mhsb.post_3",
                        verbose_name="対象記事",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",),},
        ),
        migrations.CreateModel(
            name="Comment_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        default="名無しのハンター", max_length=30, verbose_name="名前"
                    ),
                ),
                ("message", models.TextField(max_length=1000, verbose_name="本文")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mhsb.post_2",
                        verbose_name="対象記事",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",),},
        ),
        migrations.CreateModel(
            name="Comment_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        default="名無しのハンター", max_length=30, verbose_name="名前"
                    ),
                ),
                ("message", models.TextField(max_length=1000, verbose_name="本文")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mhsb.post_1",
                        verbose_name="対象記事",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",),},
        ),
    ]
